version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: singapur_airlines
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      POSTGRES_DB: singapur_airlines
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
